### ISSUE TITLE
Update Friboo and allow to pass JVM options

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/essentials#2]
- JVM: Because we want to set Hystrix timeouts
- Friboo: Because we're at it anyways.

**Comment by hjacobs** [comment]
Yes, latest Friboo has token caching :smirk:

**Comment by prayerslayer** [comment]
Actually token caching was implemented in [1.3.0](https://github.com/zalando-stups/friboo/releases/tag/1.3.0) which is already there, I just thought that once we have to deploy anyways...
